branch-defaults:
  default:
    environment: Cs3219ay2223s1ototbdocker-env
    group_suffix: null
global:
  application_name: cs3219_ay22_23_s1_otot-b_docker
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
